framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@app-test.groupe-emc.com'
        headers:
            From: 'Groupe EMC <noreply@app-test.groupe-emc.com>'
