vich_uploader:
    db_driver: orm

    mappings:
        sell_image:
            uri_prefix: /images/sales
            upload_destination: '%kernel.project_dir%/public/images/sales'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_profile_picture:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
